apiVersion: v1
kind: Service
metadata:
  name: review-feedback-service
spec:
  type: ClusterIP
  selector:
    app: review-feedback-service
  ports:
  - protocol: TCP
    port: 5632
    targetPort: 5632